- src/components/Admin/Establishment/Edit/EstablishmentEditContainer.tsx
- src/components/Admin/Establishment/Edit/EstablishmentEditPresenter.tsx
- src/domain/useCases/NumeralUseCase/NumeraUseCase.ts
- src/infrastructure/Api/Numeral/NumeralApi.ts
- src/infrastructure/Services/NumeralService.ts
No se puede actualizar las obligaciones, se agrega pero no se puede eliminar. 
-
-
-
https://github.com/user-attachments/assets/72385683-84fa-4ba2-b7a9-f377b0314dd2
> FIX: Edit numerals in forms

- src/components/Transparency/Reports/AllSolicities/AllSolicitiesPresenter.tsx
- src/components/Transparency/Solicity/All/AllSolicitiesPresenter.tsx
- src/components/Transparency/Solicity/List/SoicityListPresenter.tsx
- src/components/Transparency/Solicity/ListEstablishment/SolicityEstablishmentPresenter.tsx
Debe calcular el tiempo desde que se crea la solicitud hasta que se responde, pero no lo hace sigue contando el tiempo.
Cálculo del tiempo basado en la condición:
- Si el status es "RESPONSED", usamos updated_at como la fecha de referencia final.
- Si no, usamos la fecha actual (new Date()).
> Issue calculate date

- src/components/Transparency/Reports/AllSolicities/AllSolicitiesPresenter.tsx
- src/components/Transparency/Solicity/All/AllSolicitiesPresenter.tsx
- src/components/Transparency/Solicity/List/SoicityListPresenter.tsx
- src/components/Transparency/Solicity/ListEstablishment/SolicityEstablishmentPresenter.tsx
> Revert "Issue calculate date"

- src/components/Transparency/Reports/AllSolicities/AllSolicitiesPresenter.tsx
- src/components/Transparency/Solicity/All/AllSolicitiesPresenter.tsx
- src/components/Transparency/Solicity/List/SoicityListPresenter.tsx
- src/components/Transparency/Solicity/ListEstablishment/SolicityEstablishmentPresenter.tsx
Se intenta calcular la fecha desde el envio hasta la respuesta, pero sigue contando el tiempo. 
Cálculo del tiempo basado en la condición:
- Si el status es "RESPONSED", usamos updated_at como la fecha de referencia final.
- Si no, usamos la fecha actual (new Date()).
*Fue enviado la primera solicitud a las 12:30 y fue contestado 12:35. Como resultado tenemos 0 dias/ 0 horas*
*En el segundo caso vemos que fue enviado a las 12:40 y no fue respondido y la hora actual es 20:08. Como resultado tenemos 0 dias/ 7 horas*
**Nota Adicional:** *Se modifico las funciones en el render de calculo para que pase en el build*
> FIX: Adapter files for build

- src/components/Admin/Establishment/Edit/EstablishmentEditContainer.tsx
- src/components/Admin/Establishment/InSession/EstablishmentInSessionContainer.tsx
- src/infrastructure/Api/Establishment/EstablishmentApi.ts
- src/infrastructure/Api/Numeral/interface.ts
Se agrega typo number en `numeral.value`. y especificamos el tipo en EstablishmentDTO como `is_selected: boolean`.
> FIX: Correcion para el build

- src/components/Transparency/Active/Numerals/ActiveNumeralsPresenter.tsx
Agregar nuevo campo en el filtro.
> FIX: filtro en numerales especificos

- src/infrastructure/Services/PublicService.ts
Agregar RUC en archivos: PDF, EXCEL, CSV.
> FIX: Add RUC in CSV, PDF, Excel

- src/components/Admin/Establishment/Edit/EstablishmentEditContainer.tsx
- src/components/Admin/Establishment/Edit/EstablishmentEditPresenter.tsx
- src/components/Admin/Establishment/InSession/EstablishmentInSessionContainer.tsx
En formulario de Registro/Actualización de Instituciones para el rol "Supervisor" bloqueamos cambios en los campos mencionados en issue #27
> FIX: Block fields in rol supervisor

- src/components/Admin/Establishment/Edit/EstablishmentEditPresenter.tsx
Correccion:
- Se agrego al campo obligaciones especificas la condiciones para el rol supervisor.
#27
> FIX: Agregar la condicion en el componente obligaciones especificas

- src/domain/useCases/SolicityUseCase/SolicityUseCase.ts
Issue no reportado pero encontrado, al intentar corregir el issue#29 
Es igualacion de fechas para valicacion.
> FIX: AvaliableToProrroga condition date

- src/components/Transparency/Solicity/OnHold/SolicityOnHoldContainer.tsx
> FIX: cambio en onhold para build

- src/components/Transparency/Solicity/Response/SolicityResponsePresenter.tsx
- src/domain/mappers/SolicityMapper.ts
Agregar el componente de carga de adjuntos en prorroga.
Mapeo para la descarga del URL
> FIX: componente para cargar adjuntos y mapeo en descarga

- src/components/Admin/Users/Edit/UserEditContainer.tsx
- src/components/Admin/Users/Edit/UserEditPresenter.tsx
Desabilitamos el campo usuario para los demas perfiles con exepccion del admin
> Feat: Desabilitar el campo usuario, excepto admin

- src/utils/transform.ts
Eliminamos de esa importacion para hacer el build
> FIX: delete styles in transform files

- src/components/Dashboards/IndicatorsMonitoring/IndicatorsMonitoringPresenter.tsx
Agregue los campos faltantes para la Indicators Monitoring para build
> Fix: Agregar faltantes para build

- src/components/Admin/Establishment/Create/EstablishmentCreateContainer.tsx
- src/components/Admin/Establishment/Edit/EstablishmentEditContainer.tsx
- src/components/Admin/Establishment/Edit/EstablishmentEditPresenter.tsx
- src/components/Admin/Establishment/InSession/EstablishmentInSessionContainer.tsx
Asignamos el correo justo antes de enviar para evitar errores al momento de crear o actualizar una institucion.
> Fix: asignar directamente antes de enviar

- src/components/Common/MonthYearPicker/MonthYearPicker.tsx
Cambios para espicificar tipo en el build
> FIX: Cambios en MonthYearPicker para build

- src/components/Transparency/Solicity/Response/SolicityResponseContainer.tsx
- src/domain/useCases/SolicityUseCase/SolicityUseCase.ts
Cambios para habilitar el boton de prorroga al mismo usuario que carga.
> Fix: habilitar boton al mismo usuario que carga

- src/components/Transparency/Active/All/AllTAPresenter.tsx
Este es un test para visualizar los documentos publicados por transparencia activa. Prueba 1 aun se tiene que ajustar al requerimiento.
> Fix: mejora en vista de archivos publicados test

- src/components/Transparency/Active/All/AllTAPresenter.tsx
Prueba Nro2 de visualizacion de archivos
> Fix: vista de archivos publicados en table

- src/components/Transparency/AllPublications/AllPublicationsPresenter.tsx
> Fix: vista en archivos publicados

- src/components/Transparency/AllPublications/AllPublicationsPresenter.tsx
Extender el contenedor para que no se solapen los archivos. La idea es tener mas espacio para que los archivos puedan ser visualizados de mejor manera.
> Fix: Extender el contendor

- src/components/Transparency/AllPublications/AllPublicationsPresenter.tsx
Ajustes finales:
- Se esta eliminando los espacios entre archivos para una mejora significativa visual y cumplir con el requerimiento.
> Fix: Eliminar espacios exagerados entre archivos

- src/components/Common/HeaderPages/index.tsx
Agregamos el nombre del usuario y rol de forma informativa de acuerdo al requerimiento.
> Feat: Agregar nombre y rol en navbar

- src/components/Landing/Establishment/Detail/Publications/PublicationsPresenter.tsx
- Poder acceder a los archivos publicasdos con un hash.
Ejm:
http://pruebaspnt.dpe.gob.ec/entidades/defensoria-del-pueblo-temporal-1-2tj5#TAOctubre
Se ha agregado `#TAOctubre` de forma dinamica es decir se puede acceder a todos los meses.
Ejm:
*#TFNoviembre, #TCEnero, etc.*
> Feat: link para redirijir a las publicaciones

- src/components/Landing/Establishment/Detail/Publications/PublicationsPresenter.tsx
Revertir cambios por inestabilidad.
> Fix: Revertir cambios por inestabilidad

- src/components/Landing/Establishment/Detail/Publications/PublicationsPresenter.tsx
- Estable version en el acordion, permite cerrar y abrir de manera manual.
- Cuando se Hashea el link permite redirigir al elemento  o documento de la publicacion.
- Solo funciona cuando el componente es montado es decir, es necesario que se recargue la pagina.
*En el link al final se debe incluir las iniciales de transparencia seguida del mes.*
```
https://transparencia.dpe.gob.ec/entidades/tribunal-contencioso-electoral#TAOctubre
```
**Caso de uso:**
- TA = Transparencia activa
- TF = Transparencia focalizada
- TC = Transparencia colaborativa
*Para los meses se debe escribir de forma capitalizada y correctamente para que funcione*
Ejm --> Enero, Febrero, etc.
> Feat: Links para redireccionar archivos publicados

- src/components/Transparency/AllPublications/AllPublicationsPresenter.tsx
Normalmente los archivos cuando se publican mas de 9  la vista en el componente table se desplaza hacia la derecha provocando una dificultad para los usuarios poder acceder a dichos archivos o al boton de aceptación. Como solucion se cambia a una vista ordenada dentro de la tabla en forma vertical como se muestra a continuacion:
> Fix: Vista vertical en archivos publicados

- src/components/Common/HeaderPages/index.tsx
Feature:
- Agregamos el nombre del usuario y el rol correspondiente al lado del perfil como se solicito en el issue.
> Feat: Nombre y Rol en header

- src/components/Landing/Establishment/Detail/Publications/PublicationsPresenter.tsx
> Feat: Links para redireccionar a archivos publicados

- src/components/Admin/Establishment/Edit/EstablishmentEditContainer.tsx
- src/components/Admin/Establishment/InSession/EstablishmentInSessionContainer.tsx
Cuando el usuario borra o agrega se actualiza desde el backend y es para todos los usuarios.
> Fix: actualizar is_selected

- src/components/Transparency/Solicity/Response/SolicityResponseContainer.tsx
- src/domain/useCases/SolicityUseCase/SolicityUseCase.ts
Agregar la correccion que ya se habia hechon en la rama QA para habilitar el boton al mismo usuario que carga.
> Fix: Habilitar btn de prorroga al mismo usuario que carga

- src/components/Transparency/Solicity/Response/SolicityResponseContainer.tsx
Cuando es prorroga, se adiciona 5 días mas a la fecha de expiran para que no cambie de estado a los 10 días.
*(Versión para test y mejora)*
> Fix: adicionar 5 dias en prorroga

- src/components/Transparency/Solicity/Response/SolicityResponseContainer.tsx
> Fix: correccion para el build

- src/components/Admin/Establishment/Edit/EstablishmentEditContainer.tsx
- src/components/Admin/Establishment/Edit/EstablishmentEditPresenter.tsx
- src/components/Admin/Establishment/InSession/EstablishmentInSessionContainer.tsx
- src/components/Transparency/Active/Numerals/ActiveNumeralsPresenter.tsx
- src/domain/useCases/NumeralUseCase/NumeraUseCase.ts
- src/infrastructure/Api/Numeral/NumeralApi.ts
- src/infrastructure/Services/NumeralService.ts
- Correccion de peticion API para eliminar los numerales que se quitan del componente de seleccion. 
- Actualizacion de estado
- Usar el id de params
> FIX: Modificaciones para actualizar los numerales

- src/components/Transparency/Collaborative/List/CollaborativeListContainer.tsx
Agregar funcion faltante para cambiar de pagina en la transparencia colaborativa
> FIX: Agregar funcion para paginado

- src/components/Transparency/Solicity/Response/SolicityResponseContainer.tsx
> FIX: Respuesta de la solicitud con vista correcta

- src/components/Landing/Establishment/Detail/Information/InformationPresenter.tsx
- src/components/Landing/Establishment/Detail/PublicEstablishmentDetailPresenter.tsx
- src/components/Landing/Establishment/Detail/Publications/PublicationsPresenter.tsx
- Se coloco en el acordion una nueva pestaña `Transparencia pasiva` y se inserto el componente `InformationPresenter`. Tambien dejo abajo de dicha pestaña el `Informe anual`
> Feat: Cambios en el menu de acordion

- src/components/Landing/Establishment/Detail/PublicEstablishmentDetailPresenter.tsx
Comentar porque no se estaba usando, preparar el archivo para el build.
> FIX: Comentar declaracion sin uso

- src/components/Transparency/Collaborative/All/AllTCPresenter.tsx
- src/components/Transparency/focalized/Alll/AllTFPresenter.tsx
Agregar la misma corrección para la transparencia colaborativa y focalizada.
Tambien se cambio el titulo porque decia focalizada y era colaborativa.
> FIX: Agregar alineacion de inputs en Focalizada y Colaborativa

- src/utils/menu.tsx
> FIX: Cambios en menú vertical

- src/components/Landing/Establishment/Detail/PublicEstablishmentDetailPresenter.tsx
- src/components/Landing/Establishment/Detail/Publications/PublicationsPresenter.tsx
Cambios a nivel de vista, reorganizacion de los tags en el acordion de las publicaciones.
> Feat: Cambios en el acordion

- src/components/Transparency/Active/All/AllTAPresenter.tsx
- src/components/Transparency/Collaborative/All/AllTCPresenter.tsx
- src/components/Transparency/focalized/Alll/AllTFPresenter.tsx
Alinear los inputs en la T. Activa, T. Focalizada y T. Colaborativa desde el rol de monitoreo.
> Fix: Agregar alineacion en los inputs

- src/components/Transparency/Reports/AllSolicities/AllSolicitiesPresenter.tsx
- src/components/Transparency/Reports/SolicitiesNoResponses/SolicitiesNoResponsePresenter.tsx
- src/components/Transparency/Solicity/All/AllSolicitiesPresenter.tsx
- src/components/Transparency/Solicity/List/SoicityListPresenter.tsx
- src/components/Transparency/Solicity/ListEstablishment/SolicityEstablishmentPresenter.tsx
Detener el reloj para las insistencias respondidas.
> FIX: Detener reloj en insistencia respondida

- src/components/Landing/Establishment/Detail/PublicEstablishmentDetailContainer.tsx
Cambios para que cargue de acuerdo al mes y segun la transfarencia seleccionada.
> FIX: Correccion useEffect en carga de publicaciones

- src/components/Transparency/Active/Create/ActiveCreateContainer.tsx
- src/components/Transparency/Collaborative/Create/CollaborativeCreateContainer.tsx
- src/components/Transparency/focalized/Create/FocalizedCreateContainer.tsx
Las plantillas no están descargando con la data pre-cargada. 
Se hace modificaciones para que la data se imprima en el archivo en la columna B
> FIX: Descargar plantillas con contenido

- src/domain/useCases/SolicityUseCase/SolicityUseCase.ts
> Revision caso prorroga

- src/components/Transparency/Solicity/All/AllSolicitiesPresenter.tsx
Alinear input en Reportes T. Pasiva.
> FIX: Alinear ultimo input

- src/components/Common/Header/index.tsx
- src/components/Common/Layout/Client/index.tsx
Primer test para descargar el informe directamente desde el header
> Feat: Descargar el informe desde el header
